### ISSUE TITLE
Correctness of the output of nimgen

### ISSUE THREAD

**Issue by qingxiang-jia** [mvenditto/nimskia#1]
Amazing project! Do we know if the output of nimgen is correct? I mean, I am okay with the API being C++ centric and hard to use, but as long as it works correctly, I can start a project on top of it. Is that something we know?

**Comment by mvenditto** [comment]
Sorry for the late reply, I've been a bit busy lately!
Are you talking about generating nim binding with nimgen, directly from the Skia's C++ API (instead of the C abi)?
In that case, i remember i did couple of tests but that were a lot of manual modifications to get nimgen ingest the cpp headers. But my knowledge of cpp constructs is no that good.

If instead you're talking about nimgen output as it is in this project, it should be correct. By the C abi itself afaik it is not stable (or it was not when I started this project)

Hope it helps!

**Comment by qingxiang-jia** [comment]
Hi @mvenditto , no worries. Thanks for the reply. Yeah, I am kind of asking both. It's good to know that whatever ended up in this repository is correct and in the same time thank you for manually fixing the output of nimgen. I will close this issue.
